In [8]:
import sys
sys.path.append("..")

import pandas as pd
import nltk
from nltk.stem.snowball import FrenchStemmer

# !python3 -m spacy download fr_core_news_md
import spacy
nlp = spacy.load('fr_core_news_md')

from unidecode import unidecode

pd.set_option('display.max_rows', None)

from quotaclimat.data_analytics.analytics_signataire_charte import (
    bar_plot_nb_of_signataire_per_media, get_summary_statistics)

In [9]:
# Load dataframe
sys.path.append("..")
df_signing = pd.read_csv('../data_public/signataire_charte/generated_on=20221125/signataire_chartejournalismeecologie.csv')
df_signing.head()

,Nom,Prénom,Fonction,Média ou organisation
0,Aballain,Olivier,Directeur des formations au journalisme,ESJ Lille
1,Abalo,André,JRI,France Télévision
2,Abbiateci,Jean,Journaliste,NaN
3,Aboudou,Djamiou,Journaliste,L’Emissaire
4,Acar,Anne-Lucie,Journaliste,Free-lance

In [10]:
df_signing.Fonction.value_counts()

Journaliste                                                                                                 529
journaliste                                                                                                  54
Rédacteur en chef                                                                                            38
Rédactrice en chef                                                                                           36
Journaliste indépendante                                                                                     25
Journaliste pigiste                                                                                          20
Reporter                                                                                                     11
Pigiste                                                                                                      11
Journaliste indépendant                                                                                      11
Journaliste reporter                                                                                         10
Photographe                                                                                                   8
Étudiant                                                                                                      8
Secrétaire de rédaction                                                                                       8
Président                                                                                                     8
Rédactrice                                                                                                    7
Journaliste scientifique                                                                                      7
Photojournaliste                                                                                              7
Journaliste réalisatrice                                                                                      7
Réalisateur                                                                                                   7
Étudiant en journalisme                                                                                       7
Directrice                                                                                                    7
Journaliste environnement                                                                                     7
Étudiante                                                                                                     6
Directeur de la publication                                                                                   6
Journaliste météo                                                                                             6
Journaliste rédacteur                                                                                         6
Directeur                                                                                                     6
Etudiante                                                                                                     6
Réalisatrice                                                                                                  5
rédacteur en chef                                                                                             5
Fondatrice                                                                                                    5
Étudiante en journalisme                                                                                      4
Journaliste honoraire                                                                                         4
Rédacteur en chef adjoint                                                                                     4
Rédactrice en chef adjointe                                                                                   4
Fondateur                                                                                                     4
Grand reporter                                                                                                4
journaliste pigiste                                                                                           4
Etudiant en journalisme                                                                                       4
Directeur de la rédaction                                                                                     4
Directrice de publication                                                                                     4
Journaliste radio                                                                                             3
Directrice de la rédaction                                                                                    3
Journaliste redactrice                                                                                        3
Journaliste et auteure                                                                                        3
Co-fondatrice                                                                                                 3
Journaliste rédactrice                                                                                        3
Journaliste et autrice                                                                                        3
rédactrice en chef adjointe                                                                                   3
Présidente                                                                                                    3
Datajournaliste                                                                                               3
Directeur de publication                                                                                      3
Etudiante en journalisme                                                                                      3
Journaliste en formation                                                                                      3
Redacteur en chef                                                                                             3
Grand Reporter                                                                                                3
JOURNALISTE                                                                                                   3
Editeur                                                                                                       2
Rédacteur graphiste                                                                                           2
rédacteur                                                                                                     2
Responsable pédagogique                                                                                       2
Journaliste web                                                                                               2
Journaliste grand reporter                                                                                    2
Chef de rubrique                                                                                              2
Photographe indépendant                                                                                       2
journaliste rédactrice                                                                                        2
rédactrice en chef                                                                                            2
Gérant                                                                                                        2
JRI                                                                                                           2
rédactrice                                                                                                    2
Journaliste TV                                                                                                2
Cofondatrice                                                                                                  2
Journaliste-réalisatrice                                                                                      2
JOURNALISE                                                                                                    2
Météorologue                                                                                                  2
Journaliste Radio                                                                                             2
Chef des informations                                                                                         2
Directeur Général                                                                                             2
Realisateur                                                                                                   2
Journaliste localier                                                                                          2
Journaliste reporter d’images                                                                                 2
Alternante                                                                                                    2
Maître de conférences                                                                                         2
Journaliste présentatrice                                                                                     2
Etudiant                                                                                                      2
journaliste rédacteur                                                                                         2
Enseignant                                                                                                    2
Realisatrice                                                                                                  2
Journaliste Environnement                                                                                     2
Chef de rédaction                                                                                             2
Rédacteur-en-chef                                                                                             2
Directeur de la Publication                                                                                   2
Directrice de la Rédaction                                                                                    1
Journaliste/rédactrice                                                                                        1
Journaliste, responsable du pôle écologie                                                                     1
Journaliste agriculture                                                                                       1
Cheffe adjointe service société rédaction FTV                                                                 1
Secrétaire général                                                                                            1
Journaliste, chroniqueur radio, correspondant local                                                           1
Créateur des podcasts Baleine sous Gravillon                                                                  1
Rédactrice web et illustratrice                                                                               1
Journaliste (directeur de publication)                                                                        1
Reporter en charge de l’environnement                                                                         1
Rédac chef                                                                                                    1
Auteur d’une newsletter indépendante                                                                          1
Experte mode durable et créatrice de contenu                                                                  1
Directeur du Centre Energie                                                                                   1
Editeur et rédacteur en chef                                                                                  1
Journaliste Plantes & Santé Magazine, Journalistes-Écrivains Pour La Nature Et L’écologie (Jne)               1
Antoine                                                                                                       1
Journaliste – Productrice                                                                                     1
DG                                                                                                            1
Ex-Cheffe d’agence Sud Ouest, fondatrice de la Maison écocitoyenne des Landes                                 1
Responsable Multimédia au Master journalisme de Gennevilliers                                                 1
Journaliste reporter présentateur                                                                             1
Adhérente                                                                                                     1
Secrétaire général du Geste                                                                                   1
Journaliste, responsable de production de séries vidéo                                                        1
Journaliste RFI                                                                                               1
étudiant journaliste                                                                                          1
Présentateur des émissions                                                                                    1
Journaliste – réalisatrice                                                                                    1
Journaliste et auteur de livres sur le changement climatique                                                  1
Météorologue, présentateur météo                                                                              1
Ecrivain scientifique                                                                                         1
Journaliste, président de l’agence de presse Les Chemineurs                                                   1
planneuse stratégique                                                                                         1
Grand Reporter/ Présentatrice météo climat                                                                    1
réalisatrice                                                                                                  1
Journaliste en Formation CFPJ                                                                                 1
Enseignante-chercheuse                                                                                        1
Journaliste, adjointe au chef du service des correspondants régionaux de France télévisions                   1
Journaliste spécialisée météo/climat                                                                          1
CHEF DE SERVICE CULTURE                                                                                       1
Directeur des formations au journalisme                                                                       1
Journaliste en santé et environnement                                                                         1
Étudiant journalisme                                                                                          1
Journaliste, auteur-réalisateur et responsable innovation                                                     1
Journaliste, formateur,                                                                                       1
Journaliste éditrice                                                                                          1
Apprenti journaliste radio                                                                                    1
Émission radio                                                                                                1
Journaliste pigiste à l’étranger                                                                              1
Éditeur et journaliste                                                                                        1
Directrice de rédaction                                                                                       1
Journaliste/réalisatrice                                                                                      1
Journaliste rédactrice JRI                                                                                    1
journaliste Transition écologique et cofondateur                                                              1
Auteur-producteur de podcasts                                                                                 1
Responsable d’edition                                                                                         1
Journaliste-Auteure                                                                                           1
Journaliste pigiste / Enseignante                                                                             1
Redac cheffe                                                                                                  1
photographe                                                                                                   1
Correspondante TF1 en Inde et en Asie                                                                         1
journaliste réalisatrice                                                                                      1
Journaliste editeur et redacteur web, social manager, producteur radio                                        1
Journaliste SGR                                                                                               1
Cheffe de rubrique environnement                                                                              1
Auteur-Réalisateur-Producteur                                                                                 1
Journaliste Chef du service Documenation                                                                      1
Red chef – fondateur                                                                                          1
Journaliste-rédactrice (content manager)                                                                      1
Journaliste presse jeunesse                                                                                   1
Bimestriel de l’éconstruction                                                                                 1
journaliste auteur scénariste                                                                                 1
Rédactrice en cheffe                                                                                          1
Directeur de Publication                                                                                      1
Journaliste, rédactrice pigiste                                                                               1
MEDIA                                                                                                         1
Correspondant à Rome                                                                                          1
Professeure d’Université                                                                                      1
Journaliste vidéo spécialisée écologie et climat                                                              1
Président fondateur agence » e-crossmedia «                                                                   1
Journaliste, vice-président de Combat Le Média                                                                1
responsable environnement puis Economie sociale et solidaire du PCF, membre des JNE                           1
JOURNALISE SCIENTIFIQUE                                                                                       1
grand reporter                                                                                                1

In [15]:
def apply_stemmer(df, column_name) -> pd.DataFrame: 
    '''
    Apply a Porter Stemmer to the given column of a dataframe.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to be transformed.
    column_name : str
        The name of the column to apply the Porter Stemmer.

    Returns
    -------
    The entire dataframe, with the new column.
    '''
    # New column name
    new_column_name = f"Stemmed {column_name}"
    # Unidecode to remove accent
    df[new_column_name] = [unidecode(sentence) if pd.notna(sentence) \
        else sentence for sentence in df[column_name]]
    # Apply porter stemmer
    ps = FrenchStemmer()
    df[new_column_name] = [[ps.stem(token).capitalize() for token in sentence.split(" ")] \
        if pd.notna(sentence) else sentence for sentence in df[new_column_name]]
    # Join stemmed words
    df[new_column_name] = [" ".join(sentence) \
        if type(sentence) == list else sentence for sentence in df[new_column_name]]

    return df


def apply_lemmatizer(df, column_name) -> pd.DataFrame: 
    '''
    Lemmatize the given column of a dataframe.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to be transformed.
    column_name : str
        The name of the column to apply the lemmatization.

    Returns
    -------
    The entire dataframe, with the new column.
    '''
    # New column name
    new_column_name = f"Lemmatized {column_name}"
    # Unidecode to remove accent
    df[new_column_name] = [unidecode(sentence) if pd.notna(sentence) \
        else sentence for sentence in df[column_name]]
    # Apply porter stemmer
    df[new_column_name] = [[token.lemma_.capitalize() for token in nlp(sentence)] \
        if pd.notna(sentence) else sentence for sentence in df[new_column_name]]
    # Join stemmed words
    df[new_column_name] = [" ".join(sentence) \
        if type(sentence) == list else sentence for sentence in df[new_column_name]]

    return df

for name in ["Fonction", "Média ou organisation"]:
    df_signing = apply_stemmer(df_signing, column_name=name)
    df_signing = apply_lemmatizer(df_signing, column_name=name)
df_signing.head(25)

,Nom,Prénom,Fonction,Média ou organisation,Stemmed Fonction,Lemmatized Fonction,Stemmed Média ou organisation,Lemmatized Média ou organisation
0,Aballain,Olivier,Directeur des formations au journalisme,ESJ Lille,Directeur De Format Au Journal,Directeur De Formation Au Journalisme,Esj Lill,Esj Lille
1,Abalo,André,JRI,France Télévision,Jri,Jri,Franc Televis,France Television
2,Abbiateci,Jean,Journaliste,NaN,Journal,Journaliste,NaN,NaN
3,Aboudou,Djamiou,Journaliste,L’Emissaire,Journal,Journaliste,L'emissair,Le Emissaire
4,Acar,Anne-Lucie,Journaliste,Free-lance,Journal,Journaliste,Free-lanc,Free - Lancer
5,Ackermann,Pierre,COPIL,Demain en mains,Copil,Copil,Demain En Main,Demain En Main
6,Adaoust,Camille,Journaliste spécialisée climat-environnement,Franceinfo.fr,Journal Specialise Climat-environ,Journaliste Specialisee Climat - Environnement,Franceinfo.fr,Franceinfo.fr
7,Advocat,Raoul,journaliste,France 3,Journal,Journaliste,Franc 3,France 3
8,Aeschimann,Pierre-Eric,Journaliste,L’Obs,Journal,Journaliste,L'ob,Le Obs
9,Agorram,Laïla,Journaliste,France 3,Journal,Journaliste,Franc 3,France 3
10,Aguilar,Hélène,Fondatrice média indépendant doublé d’une asso...,Podcast Où est le beau ? * Association pour un...,Fondatric Medi Independ Doubl D'un Associ D'in...,Fondatrice Media Independer Double De Un Assoc...,Podcast Ou Est Le Beau ? * Associ Pour Un Desi...,Podcast Ou Être Le Beau ? * Association Pour U...
11,Ahamed-Mikidache,Houmi,Journaliste,Era Environnement,Journal,Journaliste,Era Environ,Era Environnement
12,Aillerie,Marie,Alterante en journalisme,"76actu, Côté Rouen",Alter En Journal,Alterante En Journalisme,"76actu, Cot Rouen","76actu , Cote Rouen"
13,Aiquel,Pablo,Journaliste,La Gazette des communes,Journal,Journaliste,La Gazet De Commun,Le Gazette De Commune
14,Ait Habbouche,Morad,Journaliste,Agence de presse Elle est pas belle la vie,Journal,Journaliste,Agenc De Press Elle Est Pas Bel La Vi,Agence De Presse Lui Être Pas Bel Le Vie
15,Ajmed Association Des Journalistes Médicaux De...,Agnès Duperrin Et Rica Etienne,co présidentes Ajmed,Ajmed,Co President Ajmed,Co Presidente Ajmed,Ajmed,Ajmed
16,Alavedra-Juncosas,Florence Laetitia,Rédactrice en chef,Feat-y,Redactric En Chef,Redactrice En Chef,Feat-y,Feat - Y
17,Albert,Marie,Journaliste,Pigiste,Journal,Journaliste,Pigist,Pigiste
18,Albertini,Clarisse,Data journaliste,Indépendante,Dat Journal,Data Journaliste,Independ,Independant
19,Alduy,Cecile,"Chercheuse, autrice",Stanford University,"Chercheuse, Autric","Chercheuse , Autrice",Stanford University,Stanford University
20,Alexandre,Matthieu,"Co-dirigeant, reporter",InTERREviews.fr,"Co-dirigeant, Report","Co-dirigeant , Reporter",Interreviews.fr,Interreviews.fr
21,Alias,Marc,Journaliste scientifique CP n°94236,Nexus,Journal Scientif Cp Ndeg94236,Journaliste Scientifique Cp Ndeg94236,Nexus,Nexus
22,Allafort,Lê Thi Mai,Rédactrice en chef,La Toque Magazine – NGPA,Redactric En Chef,Redactrice En Chef,La Toqu Magazin - Ngpa,Le Toque Magazine - Ngpa
23,Allante,Philippe,Réalisateur & documentariste,France Télévisions,Realis & Documentar,Realisateur Et Documentariste,Franc Televis,France Television
24,Allard,Laure,Étudiante en journalisme,École Du Journalisme de Nice,Etudi En Journal,Etudiante En Journalisme,Ecol Du Journal De Nic,Ecole De Journalisme De Nice

In [16]:
def check_unique_values(df, column_names):
    for name in column_names:
        print(f"Number of unique values in {name}:", len(df[name].unique()))

column_to_check = [
    "Stemmed Fonction", "Lemmatized Fonction", 
    "Stemmed Média ou organisation", "Lemmatized Média ou organisation"
]
check_unique_values(df_signing, column_to_check)

df_signing.groupby("Lemmatized Fonction").count().sort_values("Nom", ascending=False).head(50)

Number of unique values in Stemmed Fonction: 511
Number of unique values in Lemmatized Fonction: 525
Number of unique values in Stemmed Média ou organisation: 882
Number of unique values in Lemmatized Média ou organisation: 888

,Nom,Prénom,Fonction,Média ou organisation,Stemmed Fonction,Stemmed Média ou organisation,Lemmatized Média ou organisation
Lemmatized Fonction,,,,,,,
Journaliste,587,587,587,564,587,564,564
Redacteur En Chef,47,47,47,47,47,47,47
Redactrice En Chef,39,39,39,39,39,39,39
Journaliste Independant,38,38,38,31,38,31,31
Journaliste Pigist,24,24,24,19,24,19,19
Etudiante,13,13,13,13,13,13,13
Etudiant En Journalisme,13,13,13,12,13,12,12
Reporter,11,11,11,11,11,11,11
Pigiste,11,11,11,10,11,10,10
Secretaire De Redaction,10,10,10,10,10,10,10
Journaliste Environnement,10,10,10,9,10,9,9
Journaliste Reporter,10,10,10,10,10,10,10
Etudiant,10,10,10,10,10,10,10
Journaliste Scientifique,9,9,9,9,9,9,9
Redactrice,9,9,9,9,9,9,9
Journaliste Redactrice,9,9,9,9,9,9,9
Photographe,9,9,9,9,9,9,9
Realisateur,9,9,9,9,9,9,9
Directeur De Le Publication,9,9,9,9,9,9,9
Photojournaliste,8,8,8,7,8,7,7
Etudiante En Journalisme,8,8,8,8,8,8,8
Journaliste Realisatrice,8,8,8,7,8,7,7
Journaliste Redacteur,8,8,8,8,8,8,8
Realisatrice,8,8,8,7,8,7,7
Redactrice En Chef Adjoint,8,8,8,8,8,8,8
Grand Reporter,8,8,8,8,8,8,8
President,8,8,8,8,8,8,8
Directrice,7,7,7,7,7,7,7
Directeur,6,6,6,6,6,6,6
Journaliste Meteo,6,6,6,6,6,6,6
Journaliste Honoraire,5,5,5,5,5,5,5
Fondatrice,5,5,5,5,5,5,5
Journaliste Radio,5,5,5,5,5,5,5
Directrice De Le Redaction,5,5,5,5,5,5,5
Journaliste - Realisatrice,4,4,4,4,4,4,4
Directrice De Publication,4,4,4,4,4,4,4
Journaliste Et Autrice,4,4,4,4,4,4,4
Redacteur En Chef Adjoint,4,4,4,4,4,4,4
Fondateur,4,4,4,4,4,4,4
Directeur De Publication,4,4,4,4,4,4,4
Directeur De Le Redaction,4,4,4,4,4,4,4
Redacteur Graphiste,3,3,3,3,3,3,3
Co-fondatrice,3,3,3,3,3,3,3
Redacteur,3,3,3,3,3,3,3
Journaliste Web,3,3,3,2,3,2,2
Journaliste Reporter De Image,3,3,3,3,3,3,3
Maitre De Conference,3,3,3,3,3,3,3
Presidente,3,3,3,3,3,3,3
Datajournaliste,3,3,3,3,3,3,3
Journaliste En Formation,3,3,3,3,3,3,3

In [21]:
import plotly.express as px


def bar_plot_nb_of_signataire_per_media(df, column):
    count_medias = (
        df.groupby(column).count().sort_values("Nom", ascending=False)
    )
    top_n = 25
    fig = px.bar(
        count_medias.reset_index().head(top_n),
        x=column,
        y="Nom",
    )

    fig.update_xaxes(tickangle=-45, title=None)
    fig.update_yaxes(title="Nombre de personne signataire")
    fig.update_layout(
        margin={"b": 100},
        title="Nombre de signataire de la charte journalisme ecologie par média, top %s"
        % top_n,
    )
    return fig

bar_plot_nb_of_signataire_per_media(df_signing, column="Fonction")

In [22]:
bar_plot_nb_of_signataire_per_media(df_signing, column="Lemmatized Fonction")

In [16]:
bar_plot_nb_of_signataire_per_media(df_signing, column="Stemmed Fonction")